= Global Container Freight Contract Index

> Abstract

== Motivation & Reasoning


> Container Index, Futures and Volatility

- Data Quality
- Auditing
- Reproducibility
- Informational Transparency

**Data Lineage** includes the data’s origins, what happens to it and where it moves over time. Data lineage gives visibility while greatly simplifying the ability to trace errors back to the root cause in a data analytics process.

**Data Provenance** refers to records of the inputs, entities, systems, and processes that influence data of interest, providing a historical record of the data and its origins. The generated evidence supports forensic activities such as data-dependency analysis, error/compromise detection and recovery, auditing, and compliance analysis.

[source, Duke University](http://people.duke.edu/~ccc14/duke-hts-2018/bioinformatics/data_provenance.html)


=== Data Integrity and Procedures

SHA-256 hashes used properly can confirm both file integrity and authenticity
Comparing hashes makes it possible to detect changes in files that would cause errors. The possibility of changes (errors) is proportional to the size of the file; the possibility of errors increase as the file becomes larger.
[source, Ubuntu Documentation](https://help.ubuntu.com/community/HowToSHA256SUM)

==== Data Integrity Suite 

Date formats are inconsistent
An index masks underlying variation
Results have been p-hacked
Provenance is not documented
Date formats are inconsistent
Zeros replace missing values
Author is untrustworthy
Collection process is opaque
Data assert unrealistic precision


== Conventions and Specifications

Using conventions, documentation and specifications make it easier to:
- communicate the problem you are solving
- ease onboarding
- build and use composable tools
- promote open source contribution and engagement
- promote issue and feature discussion on Github itself

=== Resources

- [Drewry.co.uk](https://drewry.co.uk/)
- [Freight Trust and Clearing](https://freighttrust.com/)


== Getting Started

To get started, jump to the [drewry_container_index](/drewry_container_index) directory

---

== Contributing

How to contribute, build and release are outlined in [CONTRIBUTING.md](CONTRIBUTING.md), [BUILDING.md](BUILDING.md) and [RELEASING.md](RELEASING.md) respectively. Commits in this repository follow the [CONVENTIONAL_COMMITS.md](CONVENTIONAL_COMMITS.md) specification.

== License

2020 (C) FreightTrust and Clearing Corporation
